apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-test-app-57
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/mvaldron-rhdh/chatbot-test-app-57:d8d546a9c73c99728297408787ea7c9c9d00cd70@sha256:73efdbb122c02d6d6bd98d9043965f69f2798aba97a60e806b6aed48e030d3b3 # use pre-built to bootstrap
          name: app-inference
